{{- $persistence := .Values.persistence -}}
{{- $env := list -}}
{{- $volumes := list -}}
{{- $volumeMounts := list -}}
{{- if $persistence.enabled -}}
{{- $env = append $env (dict "name" "MINDSDB_STORAGE_DIR" "value" $persistence.mountPath) -}}
{{- $env = append $env (dict "name" "MINDSDB_CONFIG_FILE" "value" $persistence.configMountPath) -}}
{{- if eq .Values.runtimeClass "nvidia" -}}
{{- $env = append $env (dict "name" "NVIDIA_VISIBLE_DEVICES" "value" "all") -}}
{{- $env = append $env (dict "name" "NVIDIA_DRIVER_CAPABILITIES" "value" "all") -}}
{{- end -}}
{{- $volumes = list (dict "name" "config" "configMap" (dict "name" (include "common.fullname" .))) -}}
{{- $volumeMounts = list (dict "name" "config" "mountPath" $persistence.configMountPath) -}}
{{- end -}}
{{- include "common.deployment" (dict "ctx" $ "env" $env "volumes" $volumes "volumeMounts" $volumeMounts "runtimeClassName" .Values.runtimeClass) }}
