apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "influxdb-explorer.fullname" . }}
  labels:
    {{ include "influxdb-explorer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "influxdb-explorer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "influxdb-explorer.fullname" . }}
    spec:
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 6 }}
      affinity: {{ toYaml .Values.affinity | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - '--mode=admin'
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "influxdb-explorer.fullname" . }}-pvc
      {{- end }}