apiVersion: v1
kind: Service
metadata:
  name: {{ include "influxdb-explorer.fullname" . }}
  labels:
    {{- include "influxdb-explorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "influxdb-explorer.fullname" . }}
