apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "influxdb-explorer.fullname" . }}
  labels:
    {{- include "influxdb-explorer.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "influxdb-explorer.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "influxdb-explorer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "influxdb-explorer.fullname" . }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --mode=admin
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: config
              mountPath: /app-root/config
          {{- else }}
          volumeMounts:
            - name: ephemeral-data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: ephemeral-config
              mountPath: /app-root/config
          {{- end }}
      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: ephemeral-data
          emptyDir: {}
        - name: ephemeral-config
          emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "influxdb-explorer.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
    - metadata:
        name: config
        labels:
          {{- include "influxdb-explorer.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: 32Mi
      {{- if .Values.persistence.storageClass }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
  {{- end }}
