apiVersion: v2
name: aktools
description: AKTools - HTTP API for A-share market data (https://github.com/akfamily/aktools)
type: application
version: 0.2.1
appVersion: "0.0.91"
kubeVersion: ">=1.24.0-0"
home: https://github.com/akfamily/aktools
sources:
  - https://github.com/akfamily/aktools
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.1
    repository: file://../common
