{{- if and .Values.launcher.token (not .Values.launcher.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "picoclaw.launcherSecretName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.launcher.tokenKey | default "token" }}: {{ .Values.launcher.token | quote }}
{{- end }}
