apiVersion: v2
name: mindsdb
description: MindsDB - AI layer over your database (https://github.com/mindsdb/mindsdb)
type: application
version: 2.0.2
appVersion: "v26.1.0"
kubeVersion: ">=1.24.0-0"
home: https://mindsdb.com
sources:
  - https://github.com/mindsdb/mindsdb
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.1
    repository: file://../common
