{{- $fullname := include "influxdb.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-headless
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ $fullname }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ $fullname }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
