apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{ include "influxdb.labels" . | indent 4 }}
spec:
  serviceName: {{ include "influxdb.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "influxdb.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "influxdb.fullname" . }}
    spec:
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 6 }}
      affinity: {{ toYaml .Values.affinity | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - influxdb3
            - serve
            {{- if .Values.persistence.enabled }}
            - --object-store=file
            - -data-dir={{ .Values.persistence.mountPath }}/influxdb
            - -plugin-dir={{ .Values.persistence.mountPath }}/plugins
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- else }}
          volumeMounts:
            - name: ephemeral-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: ephemeral-data
          emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{ include "influxdb.labels" . | indent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
  {{- end }}
