{{- $ssPort := (first .Values.workload.ports).containerPort -}}
{{- $extraContainers := fromYamlArray (include "shadowsocks.kcptunContainer" (dict "ctx" $ "target" $ssPort)) -}}
{{- include "common.deployment" (dict "ctx" $ "env" (fromYamlArray (include "shadowsocks.env" $)) "extraContainers" $extraContainers) }}
