apiVersion: v2
name: influxdb
description: InfluxDB 3 Core with the optional InfluxDB 3 Explorer UI
type: application
version: 2.0.0
appVersion: "v3.3.0"
kubeVersion: ">=1.24.0-0"
home: https://www.influxdata.com/products/influxdb3/
sources:
  - https://github.com/influxdata/influxdb
  - https://github.com/influxdata/influxdb3-ui
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
