apiVersion: v2
name: pgone
description: pgone - a PostgreSQL wire protocol gateway (https://github.com/eslizn/pgone)
type: application
version: 0.1.3
appVersion: "62efe27"
kubeVersion: ">=1.24.0-0"
home: https://github.com/eslizn/pgone
sources:
  - https://github.com/eslizn/pgone
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.1
    repository: file://../common
