apiVersion: v2
name: shadowsocks
description: shadowsocks-libev server (https://github.com/shadowsocks/shadowsocks-libev)
type: application
version: 2.0.0
appVersion: "v3.3.5"
kubeVersion: ">=1.24.0-0"
home: https://github.com/shadowsocks/shadowsocks-libev
sources:
  - https://github.com/shadowsocks/shadowsocks-libev
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
