replicaCount: 1

image:
  repository: ghcr.io/xtls/xray-core
  pullPolicy: Always
  tag: latest

options:
  log:
    loglevel: info #warning
  inbounds:
    - protocol: vless
      port: 443
      settings:
        clients:
          - id: 87d18621-3e45-4b27-845b-e4b404cc207d
            flow: xtls-rprx-vision
        decryption: none
      sockopt:
        acceptProxyProtocol: true
      streamSettings:
        network: tcp
        security: reality
        realitySettings:
          show: true
          dest: www.microsoft.com:443
          xver: 0
          serverNames:
            - www.microsoft.com
          privateKey:
          minClientVer:
          maxClientVer:
          maxTimeDiff: 0
          shortIds:
            - aabbccdd
  outbounds:
    - protocol: freedom
    - protocol: blackhole

ingress:
  entryPoints:
    - websecure
  sni: www.microsoft.com
  port: 443

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
