replicaCount: 1

image:
  repository: ghcr.io/xtls/xray-core
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 8443

ingress:
  entryPoints: webs
  traefik: true

options:
  log:
    loglevel: warning
  inbounds:
    - protocol: vless
      port: 443
      settings:
        clients:
          - id:
            flow: xtls-rprx-vision
        decryption: none
      sockopt:
        acceptProxyProtocol: true
      streamSettings:
        network: tcp
        security: reality
        realitySettings:
          show: false
          dest: www.microsoft.com:443
          xver: 0
          serverNames:
            - www.microsoft.com
          privateKey:
          minClientVer:
          maxClientVer:
          maxTimeDiff: 0
          shortIds:
            - ""
  outbounds:
    - protocol: freedom
    - protocol: blackhole

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
