{{- if not .Values.configMapName -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "servers": {{- .Values.servers | toPrettyJson | nindent 8 }}
    }
{{- end -}}
