{{- $ports := list -}}
{{- range .Values.servers -}}
{{- $name := include "shadowsocks-rust.portName" . -}}
{{- $port := default .server_port .service_port -}}
{{- if ne (default "tcp_only" .mode) "udp_only" -}}
{{- $ports = append $ports (dict "name" (printf "%s-tcp" $name) "port" $port "targetPort" .server_port "protocol" "TCP") -}}
{{- end -}}
{{- if ne (default "tcp_only" .mode) "tcp_only" -}}
{{- $ports = append $ports (dict "name" (printf "%s-udp" $name) "port" $port "targetPort" .server_port "protocol" "UDP") -}}
{{- end -}}
{{- end -}}
{{- $main := .Values.service.main -}}
{{- include "common.service" (dict "ctx" $ "services" (dict "main" (dict "type" $main.type "annotations" $main.annotations "ports" $ports))) }}
