apiVersion: v2
name: octopus
description: Octopus - self-hosted service built from the image docker.io/eslizn/octopus
type: application
version: 0.1.0
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
