apiVersion: v2
name: xtls
description: Xray-core VLESS/REALITY proxy (https://github.com/XTLS/Xray-core)
type: application
version: 2.0.0
appVersion: "1.8.9"
kubeVersion: ">=1.24.0-0"
home: https://github.com/XTLS/Xray-core
sources:
  - https://github.com/XTLS/Xray-core
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
