apiVersion: v2
name: shadowsocks-rust
description: shadowsocks-rust server (https://github.com/shadowsocks/shadowsocks-rust)
type: application
version: 0.2.0
appVersion: "1.24.0"
kubeVersion: ">=1.24.0-0"
home: https://github.com/shadowsocks/shadowsocks-rust
sources:
  - https://github.com/shadowsocks/shadowsocks-rust
maintainers:
  - name: eslizn
    url: https://github.com/eslizn
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
