apiVersion: v1
kind: Service
metadata:
  name: {{ include "xtls.fullname" . }}
  labels:
    {{- include "xtls.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: {{ include "xtls.fullname" . }}
  selector:
    {{- include "xtls.selectorLabels" . | nindent 4 }}
{{- if .Values.ingress.traefik }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "xtls.fullname" . }}
  labels:
    {{- include "xtls.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    {{- $root := . }}
    {{- range .Values.options.inbounds }}
    {{- range .streamSettings.realitySettings.serverNames }}
    - match: HostSNI(`{{ . }}`)
      services:
        - name: {{ include "xtls.fullname" $root }}
          port: 443
          proxyProtocol:
            version: 2
    {{- end }}
    {{- end }}
  tls:
    passthrough: true
{{- end }}