apiVersion: v1
kind: Service
metadata:
  name: {{ include "xtls.fullname" . }}
  labels:
    {{- include "xtls.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "xtls.selectorLabels" . | nindent 4 }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "xtls.fullname" . }}
  labels:
    {{- include "xtls.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.service.entryPoints | nindent 4 }}
  routes:
    - match: HostSNI(`{{ .Values.service.sni }}`)
      services:
        - name: {{ include "xtls.fullname" . }}
          port: {{ .Values.service.port }}
          proxyProtocol:
            version: 2
  tls:
    passthrough: true
